ts-sp-fwu: Set correct SRCREV
Issue: LINUXEXEC-33015

Use v2.7.0 as SRCREV caused errors when call bb.fetch.decodeurl() without
network (BB_NO_NETWORK = "1"):

Exception: bb.fetch2.NetworkAccess: Network access disabled through
BB_NO_NETWORK (or set indirectly due to use of BB_FETCH_PREMIRRORONLY) but
access requested with command git -c gc.autoDetach=false -c core.pager=cat -c
safe.bareRepository=all ls-remote
https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git  (for url
https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git)

(LOCAL REV: NOT UPSTREAM) - Will send to upstream later.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>